// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2._sem_projekt_boglistesystemet.Models;

#nullable disable

namespace _2.semprojektboglistesystemet.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20221130175225_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FagUnderviser", b =>
                {
                    b.Property<int>("FagId")
                        .HasColumnType("int");

                    b.Property<int>("UnderviserId")
                        .HasColumnType("int");

                    b.HasKey("FagId", "UnderviserId");

                    b.HasIndex("UnderviserId");

                    b.ToTable("FagUnderviser");
                });

            modelBuilder.Entity("HoldSemestre", b =>
                {
                    b.Property<int>("HoldId")
                        .HasColumnType("int");

                    b.Property<int>("semestreSemesterId")
                        .HasColumnType("int");

                    b.HasKey("HoldId", "semestreSemesterId");

                    b.HasIndex("semestreSemesterId");

                    b.ToTable("HoldSemestre");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Boghandler", b =>
                {
                    b.Property<int>("BoghandlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoghandlerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<int>("password")
                        .HasColumnType("int");

                    b.HasKey("BoghandlerId");

                    b.ToTable("Boghandlere");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.BookData.Underviser", b =>
                {
                    b.Property<int>("UnderviserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnderviserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Initials")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("KoordinatorId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UnderviserId");

                    b.HasIndex("KoordinatorId");

                    b.ToTable("Undervisere");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Books", b =>
                {
                    b.Property<int>("BogId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BogId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BoghandlerId")
                        .HasColumnType("int");

                    b.Property<int?>("ISBN")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UnderviserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("BogId");

                    b.HasIndex("BoghandlerId");

                    b.HasIndex("UnderviserId");

                    b.ToTable("Bøger");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Fag", b =>
                {
                    b.Property<int>("FagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FagId"));

                    b.Property<int?>("KoordinatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FagId");

                    b.HasIndex("KoordinatorId");

                    b.ToTable("Fag");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Hold", b =>
                {
                    b.Property<int>("HoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoldId"));

                    b.Property<int?>("KoordinatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HoldId");

                    b.HasIndex("KoordinatorId");

                    b.ToTable("Hold");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Koordinator", b =>
                {
                    b.Property<int>("KoordinatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoordinatorId"));

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.HasKey("KoordinatorId");

                    b.ToTable("Koordinatorer");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Semestre", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<int?>("KoordinatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UddannelserUddannelseId")
                        .HasColumnType("int");

                    b.HasKey("SemesterId");

                    b.HasIndex("KoordinatorId");

                    b.HasIndex("UddannelserUddannelseId");

                    b.ToTable("Semestre");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Uddannelser", b =>
                {
                    b.Property<int>("UddannelseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UddannelseId"));

                    b.Property<int?>("KoordinatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UddannelseId");

                    b.HasIndex("KoordinatorId");

                    b.ToTable("Uddannelser");
                });

            modelBuilder.Entity("FagUnderviser", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Fag", null)
                        .WithMany()
                        .HasForeignKey("FagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.BookData.Underviser", null)
                        .WithMany()
                        .HasForeignKey("UnderviserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HoldSemestre", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Hold", null)
                        .WithMany()
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Semestre", null)
                        .WithMany()
                        .HasForeignKey("semestreSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.BookData.Underviser", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Koordinator", null)
                        .WithMany("Undervisers")
                        .HasForeignKey("KoordinatorId");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Books", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Boghandler", null)
                        .WithMany("Books")
                        .HasForeignKey("BoghandlerId");

                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.BookData.Underviser", null)
                        .WithMany("Books")
                        .HasForeignKey("UnderviserId");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Fag", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Koordinator", null)
                        .WithMany("Fag")
                        .HasForeignKey("KoordinatorId");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Hold", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Koordinator", null)
                        .WithMany("Hold")
                        .HasForeignKey("KoordinatorId");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Semestre", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Koordinator", null)
                        .WithMany("semestres")
                        .HasForeignKey("KoordinatorId");

                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Uddannelser", null)
                        .WithMany("semestres")
                        .HasForeignKey("UddannelserUddannelseId");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Uddannelser", b =>
                {
                    b.HasOne("_2._sem_projekt_boglistesystemet.Models.Koordinator", null)
                        .WithMany("uddannelser")
                        .HasForeignKey("KoordinatorId");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Boghandler", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.BookData.Underviser", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Koordinator", b =>
                {
                    b.Navigation("Fag");

                    b.Navigation("Hold");

                    b.Navigation("Undervisers");

                    b.Navigation("semestres");

                    b.Navigation("uddannelser");
                });

            modelBuilder.Entity("_2._sem_projekt_boglistesystemet.Models.Uddannelser", b =>
                {
                    b.Navigation("semestres");
                });
#pragma warning restore 612, 618
        }
    }
}
